terminal_source: usart2
software_timer:
  priority: 2
  stack_depth: 512
SPI:
  spi1:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_enable_min_size: 3
  spi3:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_enable_min_size: 3
USART:
  usart1:
    tx_buffer_size: 128
    rx_buffer_size: 128
    tx_queue_size: 5
    rx_queue_size: 5
  usart2:
    tx_buffer_size: 128
    rx_buffer_size: 128
    tx_queue_size: 5
    rx_queue_size: 5
Terminal:
  READ_BUFF_SIZE: 32
  MAX_LINE_SIZE: 32
  MAX_ARG_NUMBER: 5
  MAX_HISTORY_NUMBER: 5
SYSTEM: FreeRTOS
