terminal_source: usart2
software_timer:
  priority: 2
  stack_depth: 512
SPI:
  spi1:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_enable_min_size: 3
    dma_section: ''
  spi3:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_enable_min_size: 3
    dma_section: ''
USART:
  usart1:
    tx_buffer_size: 128
    rx_buffer_size: 128
    tx_queue_size: 5
    rx_queue_size: 5
    dma_section: ''
  usart2:
    tx_buffer_size: 128
    rx_buffer_size: 128
    tx_queue_size: 5
    rx_queue_size: 5
    dma_section: ''
FDCAN:
  FDCAN1:
    queue_size: 5
Terminal:
  READ_BUFF_SIZE: 32
  MAX_LINE_SIZE: 32
  MAX_ARG_NUMBER: 5
  MAX_HISTORY_NUMBER: 5
  RunAsThread: true
  ThreadStackDepth: 4096
  ThreadPriority: 3
SYSTEM: FreeRTOS
FlashLayout:
  model: STM32G431KBU6
  flash_base: '0x08000000'
  flash_size_kb: 128
  sectors:
  - index: 0
    address: '0x08000000'
    size_kb: 2.0
  - index: 1
    address: '0x08000800'
    size_kb: 2.0
  - index: 2
    address: '0x08001000'
    size_kb: 2.0
  - index: 3
    address: '0x08001800'
    size_kb: 2.0
  - index: 4
    address: '0x08002000'
    size_kb: 2.0
  - index: 5
    address: '0x08002800'
    size_kb: 2.0
  - index: 6
    address: '0x08003000'
    size_kb: 2.0
  - index: 7
    address: '0x08003800'
    size_kb: 2.0
  - index: 8
    address: '0x08004000'
    size_kb: 2.0
  - index: 9
    address: '0x08004800'
    size_kb: 2.0
  - index: 10
    address: '0x08005000'
    size_kb: 2.0
  - index: 11
    address: '0x08005800'
    size_kb: 2.0
  - index: 12
    address: '0x08006000'
    size_kb: 2.0
  - index: 13
    address: '0x08006800'
    size_kb: 2.0
  - index: 14
    address: '0x08007000'
    size_kb: 2.0
  - index: 15
    address: '0x08007800'
    size_kb: 2.0
  - index: 16
    address: '0x08008000'
    size_kb: 2.0
  - index: 17
    address: '0x08008800'
    size_kb: 2.0
  - index: 18
    address: '0x08009000'
    size_kb: 2.0
  - index: 19
    address: '0x08009800'
    size_kb: 2.0
  - index: 20
    address: '0x0800A000'
    size_kb: 2.0
  - index: 21
    address: '0x0800A800'
    size_kb: 2.0
  - index: 22
    address: '0x0800B000'
    size_kb: 2.0
  - index: 23
    address: '0x0800B800'
    size_kb: 2.0
  - index: 24
    address: '0x0800C000'
    size_kb: 2.0
  - index: 25
    address: '0x0800C800'
    size_kb: 2.0
  - index: 26
    address: '0x0800D000'
    size_kb: 2.0
  - index: 27
    address: '0x0800D800'
    size_kb: 2.0
  - index: 28
    address: '0x0800E000'
    size_kb: 2.0
  - index: 29
    address: '0x0800E800'
    size_kb: 2.0
  - index: 30
    address: '0x0800F000'
    size_kb: 2.0
  - index: 31
    address: '0x0800F800'
    size_kb: 2.0
  - index: 32
    address: '0x08010000'
    size_kb: 2.0
  - index: 33
    address: '0x08010800'
    size_kb: 2.0
  - index: 34
    address: '0x08011000'
    size_kb: 2.0
  - index: 35
    address: '0x08011800'
    size_kb: 2.0
  - index: 36
    address: '0x08012000'
    size_kb: 2.0
  - index: 37
    address: '0x08012800'
    size_kb: 2.0
  - index: 38
    address: '0x08013000'
    size_kb: 2.0
  - index: 39
    address: '0x08013800'
    size_kb: 2.0
  - index: 40
    address: '0x08014000'
    size_kb: 2.0
  - index: 41
    address: '0x08014800'
    size_kb: 2.0
  - index: 42
    address: '0x08015000'
    size_kb: 2.0
  - index: 43
    address: '0x08015800'
    size_kb: 2.0
  - index: 44
    address: '0x08016000'
    size_kb: 2.0
  - index: 45
    address: '0x08016800'
    size_kb: 2.0
  - index: 46
    address: '0x08017000'
    size_kb: 2.0
  - index: 47
    address: '0x08017800'
    size_kb: 2.0
  - index: 48
    address: '0x08018000'
    size_kb: 2.0
  - index: 49
    address: '0x08018800'
    size_kb: 2.0
  - index: 50
    address: '0x08019000'
    size_kb: 2.0
  - index: 51
    address: '0x08019800'
    size_kb: 2.0
  - index: 52
    address: '0x0801A000'
    size_kb: 2.0
  - index: 53
    address: '0x0801A800'
    size_kb: 2.0
  - index: 54
    address: '0x0801B000'
    size_kb: 2.0
  - index: 55
    address: '0x0801B800'
    size_kb: 2.0
  - index: 56
    address: '0x0801C000'
    size_kb: 2.0
  - index: 57
    address: '0x0801C800'
    size_kb: 2.0
  - index: 58
    address: '0x0801D000'
    size_kb: 2.0
  - index: 59
    address: '0x0801D800'
    size_kb: 2.0
  - index: 60
    address: '0x0801E000'
    size_kb: 2.0
  - index: 61
    address: '0x0801E800'
    size_kb: 2.0
  - index: 62
    address: '0x0801F000'
    size_kb: 2.0
  - index: 63
    address: '0x0801F800'
    size_kb: 2.0
device_aliases:
  power_manager:
    type: PowerManager
    aliases:
    - power_manager
  BMI088_CS_2:
    type: GPIO
    aliases:
    - bmi088_gyro_cs
  BMI088_INT_1:
    type: GPIO
    aliases:
    - bmi088_accl_int
  IMU_CS:
    type: GPIO
    aliases:
    - icm42688_cs
  IMU_INT1:
    type: GPIO
    aliases:
    - icm42688_int
  BMI088_CS_1:
    type: GPIO
    aliases:
    - bmi088_accl_cs
  BMI088_INT_2:
    type: GPIO
    aliases:
    - bmi088_gyro_int
  LED:
    type: GPIO
    aliases:
    - LED
  pwm_tim1_ch1:
    type: PWM
    aliases:
    - pwm_bmi088_heat
  pwm_tim2_ch2:
    type: PWM
    aliases:
    - pwm_icm42688_heat
  spi1:
    type: SPI
    aliases:
    - spi_icm42688
  spi3:
    type: SPI
    aliases:
    - spi_bmi088
  usart1:
    type: UART
    aliases:
    - usart1
  usart2:
    type: UART
    aliases:
    - usart2
  fdcan1:
    type: FDCAN
    aliases:
    - fdcan1
  ramfs:
    type: RamFS
    aliases:
    - ramfs
  terminal:
    type: Terminal<32, 32, 5, 5>
    aliases:
    - terminal
