terminal_source: usart2
software_timer:
  priority: 2
  stack_depth: 512
SPI:
  spi1:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_enable_min_size: 3
  spi3:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_enable_min_size: 3
USART:
  usart1:
    tx_buffer_size: 128
    rx_buffer_size: 128
    tx_queue_size: 5
    rx_queue_size: 5
  usart2:
    tx_buffer_size: 128
    rx_buffer_size: 128
    tx_queue_size: 5
    rx_queue_size: 5
Terminal:
  READ_BUFF_SIZE: 32
  MAX_LINE_SIZE: 32
  MAX_ARG_NUMBER: 5
  MAX_HISTORY_NUMBER: 5
SYSTEM: FreeRTOS
device_aliases:
  power_manager:
    type: PowerManager
    aliases:
    - power_manager
  BMI088_CS_2:
    type: GPIO
    aliases:
    - bmi088_gyro_cs
  BMI088_INT_1:
    type: GPIO
    aliases:
    - bmi088_accl_int
  IMU_CS:
    type: GPIO
    aliases:
    - IMU_CS
  IMU_INT1:
    type: GPIO
    aliases:
    - IMU_INT1
  BMI088_CS_1:
    type: GPIO
    aliases:
    - bmi088_accl_cs
  BMI088_INT_2:
    type: GPIO
    aliases:
    - bmi088_gyro_int
  LED:
    type: GPIO
    aliases:
    - LED
  pwm_tim1_ch1:
    type: PWM
    aliases:
    - pwm_bmi088_heat
  pwm_tim2_ch2:
    type: PWM
    aliases:
    - pwm_tim2_ch2
  spi1:
    type: SPI
    aliases:
    - spi1
  spi3:
    type: SPI
    aliases:
    - spi_bmi088
  usart1:
    type: UART
    aliases:
    - usart1
  usart2:
    type: UART
    aliases:
    - usart2
  fdcan1:
    type: FDCAN
    aliases:
    - fdcan1
  ramfs:
    type: RamFS
    aliases:
    - ramfs
  terminal:
    type: Terminal<32, 32, 5, 5>
    aliases:
    - terminal
